config/routes.rb
Rails.application.routes.draw do
  resources :cashbook_indices
  root 'cashbook_indices#new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashbook_index.rb
class CashbookIndex < ApplicationRecord
	attr_accessor :credit_attributes, :debit_attributes
	before_save :reject_action
	belongs_to :user

	

	has_many :credits, inverse_of: :cashbook_index
	has_many :debits, inverse_of: :cashbook_index
	has_many :closing_cashes, inverse_of: :cashbook_index

	accepts_nested_attributes_for :credits, :debits, :closing_cashes

	validates_associated :credits, :debits, :closing_cashes



	
#   def next
#    	CashbookIndex.where("id > ?", id).order("id ASC").first || CashbookIndex.first
# 	end

  	def previous
    	# CashbookIndex.where("id < ?", id).order("id DESC").first || CashbookIndex.last
    	CashbookIndex.where("id < ?", id).order("id DESC").first || CashbookIndex.last

  	end

  	def reject_action
		credits.each do |credit|
			credit.destroy if credit.particular_name.blank?
		end
		debits.each do |debit|
			debit.destroy if debit.particular_name.blank?
		end
  	end
end

app/models/closing_cash.rb
class ClosingCash < ApplicationRecord
	belongs_to :cashbook_index, inverse_of: :closing_cashes


end

app/models/credit.rb
class Credit < ApplicationRecord
	belongs_to :cashbook_index, inverse_of: :credits
end

app/models/debit.rb
class Debit < ApplicationRecord
	belongs_to :cashbook_index, inverse_of: :debits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   	has_many :cashbook_indices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cashbook_indices_controller.rb
class CashbookIndicesController < ApplicationController
 

  before_action :set_cashbook_index, only: [:show, :edit, :update, :destroy]

  # GET /cashbook_indices
  # GET /cashbook_indices.json
  def index

    @cashbook_indices = current_user.cashbook_indices.all

  end


  # GET /cashbook_indices/1
  # GET /cashbook_indices/1.json
  def show
    @cashbook_index = current_user.cashbook_indices.find(params[:id])
    @credits = @cashbook_index.credits.all
    @debits = @cashbook_index.debits.all
    @closing_cashes = @cashbook_index.closing_cashes.all
    
  end

  # GET /cashbook_indices/new
  def new
    @cashbook_index = CashbookIndex.new
    
    15.times do 
      @cashbook_index.credits.new
      @cashbook_index.debits.new
    end
    10.times do
      # @cashbook_index.opening_cashes.new
      @cashbook_index.closing_cashes.new
    end
  end

  # GET /cashbook_indices/1/edit
  def edit
    15.times do 
      @cashbook_index.credits.new
      @cashbook_index.debits.new
    end
  end

  # POST /cashbook_indices
  # POST /cashbook_indices.json
  def create
    @cashbook_index = CashbookIndex.new(cashbook_index_params)
    @cashbook_index.user = current_user
    respond_to do |format|
      if @cashbook_index.save
        format.html { redirect_to @cashbook_index, notice: 'Cashbook index was successfully created.' }
        format.json { render :show, status: :created, location: @cashbook_index }
      else
        format.html { render :new }
        format.json { render json: @cashbook_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashbook_indices/1
  # PATCH/PUT /cashbook_indices/1.json
  def update
    respond_to do |format|
      if @cashbook_index.update(cashbook_index_params)
        format.html { redirect_to @cashbook_index, notice: 'Cashbook index was successfully updated.' }
        format.json { render :show, status: :ok, location: @cashbook_index }
      else
        format.html { render :edit }
        format.json { render json: @cashbook_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashbook_indices/1
  # DELETE /cashbook_indices/1.json
  def destroy
    @cashbook_index.destroy
    respond_to do |format|
      format.html { redirect_to cashbook_indices_url, notice: 'Cashbook index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashbook_index
      @cashbook_index = CashbookIndex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cashbook_index_params
      params.require(:cashbook_index).permit(:id, :user_id, :cr_total, :dr_total, :cash_in_hand, :closing_total, :credits_attributes => [:id, :_destroy, :cashbook_index_id, :particular_name, :reference, :amount, :total], :debits_attributes => [:id, :_destroy, :cashbook_index_id, :particular_name, :reference, :amount, :total], :closing_cashes_attributes => [:id, :_destroy, :cashbook_index_id, :denomination, :quantity, :total] )
      # params.require(:cashbook_index).permit(:id, :cr_total, :dr_total, :cash_in_hand, :credits_attributes => [:id, :_destroy, :user_id, :cashbook_index_id, :particular_name, :reference, :amount, :total], :debits_attributes => [:id, :_destroy, :user_id, :cashbook_index_id, :particular_name, :reference, :amount, :total], :opening_cashes_attributes => [:id, :_destroy, :user_id, :cashbook_index_id, :denomination, :quantity, :total], :closing_cashes_attributes => [:id, :_destroy, :user_id, :cashbook_index_id, :denomination, :quantity, :total] )
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashbook_indices_helper.rb
module CashbookIndicesHelper
end

app/views/cashbook_indices/_closing_cashes.html.erb
<tr class="item-row">

	<td><%= f.number_field :denomination, label: false, :readonly => true, class: "form-control denomination" %></td>
	<td><%= f.number_field :quantity, label: false, min: "0", class: "form-control quantity" %></td>
	<td><%= f.number_field :total, label: false, :readonly => true, value: "0.0", class: "form-control closing-amount" %></td>
	<td><%= f.hidden_field :cashbook_index_id, label: false %></td>

<tr>

app/views/cashbook_indices/_credit.html.erb
<tr class="item-row">
	<td><%= f.text_field :particular_name, label: false, class: "form-control particular" %></td>
	<td><%= f.text_field :reference, label: false, class: "form-control reference" %></td>
	<td><%= f.number_field :amount, label: false, min: "0", class: "form-control credit-amount" %></td>
	<td><%= f.hidden_field :cashbook_index_id, label: false, class: "" %></td>
</tr>

app/views/cashbook_indices/_debit.html.erb
<tr class="item-row">

  	<td><%= f.text_field :particular_name, label: false, class: "form-control particular" %></td>
	<td><%= f.text_field :reference, label: false, class: "form-control reference" %></td>
	<td><%= f.number_field :amount, label: false, min: "0", class: "form-control debit-amount" %></td>
	<td><%= f.hidden_field :cashbook_index_id, label: false, class: "form-control" %></td>
</tr>

app/views/cashbook_indices/_form.html.erb
<style> 
.ex1 {
/*  background-color: gray;*/
  height: 450px;
  width: 100%;
  overflow-y: scroll;
}
.col-md-4{
  padding-right: 8px;
  padding-left: 8px;
}

</style>

<% @diff = @cashbook_index.closing_total.to_i - @cashbook_index.cash_in_hand.to_i %>
<% if @cashbook_index.previous.present? %>
  <% @prev_diff = @cashbook_index.previous.closing_total.to_i - @cashbook_index.previous.cash_in_hand.to_i %>
  <% @prev_cash_in_hand = @cashbook_index.previous.cash_in_hand.to_i %>
<% end %>

<%= form_for @cashbook_index, :html => { id: "feedbackform" } do |f| %>
  <% if cashbook_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cashbook_index.errors.count, "error") %> prohibited this cashbook_index from being saved:</h2>

      <ul>
      <% cashbook_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
  <div class="row heading">
    <div class="col-md-3">
      <strong class="border-b-padding-10px">CASH IN HAND: Cr - Dr = &nbsp&nbsp<i class="fa fa-inr"></i>&nbsp<%= @prev_cash_in_hand %></strong>
    </div>
    <div class="col-md-6">
      <center><h3 class="text-shadow">CASH BOOK</h3></center>
    </div>
    <div class="col-md-3">
      <strong class="pull-right">
          <%= link_to "All", cashbook_indices_path, class: "index" %>&nbsp&nbsp
          <span class="border-b-padding-10px"><%= Time.now.strftime("%d-%m-%Y") %></span>
      </strong>
    </div>
  </div>
  </div>
<div class="col-md-12">
  <div class="row padding-1">
    <div class="col-md-4">
      <center><strong>CREDIT</strong></center>
    </div>
    <div class="col-md-4">
      <center><strong>DEBIT</strong></center>
    </div>
    <div class="col-md-2">
      <center><strong>CLOSING CASH TABLE</strong></center>
    </div>
    <div class="col-md-2">
      <center><strong>OPENING CASH TABLE</strong></center>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <table class="table table-hover">
          <thead>
              <th class="text-align-center">PARTICULARS</th>
              <th class="text-align-center">REFERENCE</th>
              <th>AMOUNT</th>
          </thead>
        </table>
        <div class="ex1">
          <table class="table table-hover">
            <tbody class='credits_fields'>
              <%= f.fields_for :credits do |builder| %>
                <%= render 'credit', f: builder  %>
              <% end %>
            </tbody>
          </table>
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>

              <td>CREDIT TOTAL: </td>
              <td><i class="fa fa-inr pull-right"></i></td>
              <td><%= f.number_field :cr_total, label: false, :readonly => true, class: "form-control credit-grandTotal", style: " width: 50%; float: right" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-4">
        <table class="table table-hover">
          <thead>
            <th class="text-align-center">PARTICULARS</th>
            <th class="text-align-center">REFERENCE</th>
            <th>AMOUNT</th>
          </thead>
        </table>
        <div class="ex1">
          <table class="table table-hover">
            <tbody class='debits_fields'>
              <%= f.fields_for :debits do |builder| %>
                <%= render 'debit', f: builder  %>
              <% end %>
            </tbody>
          </table>  
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <td>DEBIT TOTAL: <i class="fa fa-inr pull-right"></i></td>
              <td><%= f.number_field :dr_total, label: false, :readonly => true, class: "form-control debit-grandTotal" %></td>
            </tr>

            <tr>
              <td>BALANCE C/F: <i class="fa fa-inr pull-right"></i></td>
              <td><%= f.number_field :cash_in_hand, label: false, :readonly => true, class: "form-control cash-in-hand-total" %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-4">
          <div class="row">
            <div class="col-md-6">
              <table class="table table-hover table-padding" title="closing_cashes">
                <thead class="text-align-center">
                  <th>VALUE</th>
                  <th>QTY</th>
                  <th>TOTAL</th>
                </thead>
                <tbody class='fields'>
                  <%= f.fields_for :closing_cashes do |builder| %>
                    <%= render 'closing_cashes', f: builder  %>
                  <% end %>
                </tbody>
              </table>
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <td colspan="2">GRAND TOTAL:</td>
                    <td><%= f.number_field :closing_total, label: false, :readonly => true, class: "form-control closing_cashesgrandtotal" %></td>
                  </tr>
                  <tr>
                      <td colspan="2">DIFFERENCE:</td>
                      <td><i class="fa fa-inr"></i>&nbsp<span class="differenceofcashclosing"></span></td> 
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <table class="table table-hover table-padding" title="opening_cashes">
                <thead class="text-align-center">
                    <th>VALUE</th>
                    <th>QTY</th>
                    <th>TOTAL</th>
                </thead>
                <tbody class='fields'>
                  <% if @cashbook_index.previous.present? %>
                    <% @cashbook_index.previous.closing_cashes.each do |credit| %>
                      <tr>
                        <td class="closing-cashes-table"><%= credit.denomination %></td>
                        <td class="closing-cashes-table"><%= credit.quantity %></td>
                        <td class="closing-cashes-table closing-total"><%= credit.total %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <td colspan="2">GRAND TOTAL:</td>
                    <td class="text-align-center"><i class="fa fa-inr"></i>&nbsp&nbsp<%= @cashbook_index.previous.present? ? @cashbook_index.previous.closing_total : 0 %> </td>
                  </tr>
                  <tr>
                    <td colspan="2">DIFFERENCE:</td>
                    <td class="text-align-center"><i class="fa fa-inr"></i>&nbsp&nbsp<%= @prev_diff %></td> 
                  </tr>
                </tbody>
             </table>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="col-md-12">
                <%= f.button "submit", class: "btn btn-dark pull-right" %>
              </div>
            </div>
          </div>
       
      </div>
    </div>
  </div>
</div>



<% end %>

                     

app/views/cashbook_indices/edit.html.erb
<%= render 'form', cashbook_index: @cashbook_index %>

app/views/cashbook_indices/index.html.erb
<style> 
.ex1 {
/*  background-color: gray;*/
  height: 450px;
  width: 100%;
  overflow-y: scroll;
}
.col-md-4{
  padding-right: 8px;
  padding-left: 8px;
}

</style>

<div class="col-md-12">
  <div class="row heading">

    <div class="col-md-11">
      <h3 class="text-shadow">CASH BOOKS</h3>
    </div>
    <div class="col-md-1 text-align-right">
      <%= link_to "", new_cashbook_index_path, class: "fa fa-plus" %>

<!-- 
      <%= link_to "Excel", cashbook_indices_path(format: "xlsx") %> -->
    </div>
    
  </div>
</div>
<br>
<style type="text/css">
  .table td{border-top: 1px solid gray;}
</style>
<div class="col-md-12">
  <table class="table table-hover" id="cashbook_index">
    <thead>
      <tr class="text-align-center">
        <td>ID</td>
        <td>DATE</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @cashbook_indices.each do |cashbook_index| %>
        <tr class="text-align-center">
          <td><%= cashbook_index.id %></td>
          <td><%= cashbook_index.created_at.strftime("%d/%m/%y") %></td>
          <td>
            <span class="pull-right">
            <%= link_to '', cashbook_index, class: "fa fa-eye" %>
            <%= link_to '', edit_cashbook_index_path(cashbook_index), class: "fa fa-pencil" %>
            <%= link_to '', cashbook_index, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash" %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cashbook_indices/new.html.erb
<%= render 'form', cashbook_index: @cashbook_index %>

app/views/cashbook_indices/show.html.erb
<style> 
.col-md-4{
  padding-right: 8px;
  padding-left: 8px;
}
.ex1 {
/*  background-color: gray;*/
  height: 405px;
  width: 100%;
  overflow-y: scroll;
}



</style>


<% @diff = @cashbook_index.closing_total.to_i - @cashbook_index.cash_in_hand.to_i%>
<% if @cashbook_index.previous.present? %>
<% @prev_diff = @cashbook_index.previous.closing_total.to_i - @cashbook_index.previous.cash_in_hand.to_i %>
<% @prev_cash_in_hand = @cashbook_index.previous.cash_in_hand.to_i %>
<% end %>
<div class="col-md-12">
  <div class="row heading">
    <div class="col-md-3">
      <strong class="border-b-padding-10px">CASH IN HAND: Cr - Dr = <i class="fa fa-inr"></i>&nbsp<%= @prev_cash_in_hand %></strong>
    </div>
    <div class="col-md-6">
      <center><h3 class="text-shadow">CASH BOOK</h3></center>
    </div>
    <div class="col-md-3">

      <strong style="float: right;">
        <span><%= link_to "", new_cashbook_index_path, class: "fa fa-plus" %></span>&nbsp&nbsp
        <span><%= link_to '', edit_cashbook_index_path(@cashbook_index), class: "fa fa-pencil" %></span>&nbsp&nbsp
        <%= @cashbook_index.created_at.strftime("%d-%m-%Y") %></strong>
    </div>
  </div>
</div>
    <br>
<div class="col-md-12">
  <div class="row ">
    <div class="col-md-4">
      <center><strong>CREDIT</strong></center>
    </div>
    <div class="col-md-4">
      <center><strong>DEBIT</strong></center>
    </div>
    <div class="col-md-2">
      <center><strong>CLOSING CASH TABLE</strong></center>
    </div>
    <div class="col-md-2">
      <center><strong>OPENING CASH TABLE</strong></center>
    </div>
  </div>
</div>
<br>
<div class="container-fluid" id="cashbook">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <table class="table table-hover">
          <thead>
              <th>PARTICULARS</th>
              <th>REFERENCE</th>
              <th>AMOUNT</th>
          </thead>
        </table>
        <div class="ex1">
          <table class="table table-hover" border="1">
           
            <tbody class='credits_fields'>
              <% @credits.each do |credit| %>
                <tr>
                  <td><%= credit.particular_name %></td>
                  <td><%= credit.reference %></td>
                  <td class="debit-amount"><%= credit.amount %></td>
                </tr>
              <% end %>
            </tbody>
           
          </table>
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <td>CREDIT TOTAL: </td>
              <td><i class="fa fa-inr pull-right"></i></td>
              <td><%= @cashbook_index.cr_total %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-4">
        <table class="table table-hover">
          <thead>
                <th>PARTICULARS</th>
                <th>REFERENCE</th>
                <th>AMOUNT</th>
            </thead>
          
        </table>
        <div class="ex1">
          <table class="table table-hover" border="1">
            
            <tbody class='debits_fields'>
              <% @debits.each do |credit| %>
                <tr>
                  <td><%= credit.particular_name %></td>
                  <td><%= credit.reference %></td>
                  <td class="debit-amount"><%= credit.amount %></td>
                </tr>
              <% end %>
            </tbody>
            
          </table>  
        </div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <td>DEBIT TOTAL: <i class="fa fa-inr pull-right"></i></td>
              <td style="text-align: center;"><%= @cashbook_index.dr_total %></td>
            </tr>

            <tr>
              <td>BALANCE C/F: <i class="fa fa-inr pull-right"></i></td>
              <td style="text-align: center"><%= @cashbook_index.cash_in_hand %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-4">
          <div class="row">
            
            <div class="col-md-6">
               <table class="table table-hover table-padding" title="closing_cashes">
                <thead>
                  <th>VALUE</th>
                  <th>QTY</th>
                  <th>TOTAL</th>
                </thead>
                
                <tbody class='fields closing'>
                  <% @closing_cashes.each do |credit| %>
                    <tr>
                      <td><%= credit.denomination %></td>
                      <td><%= credit.quantity %></td>
                      <td><%= credit.total %></td>
                    </tr>
                  <% end %>
                </tbody>
                
              </table>
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <td colspan="2">GRAND TOTAL:</td>
                    <td><i class="fa fa-inr"></i>&nbsp<%= @cashbook_index.closing_total %></td>
                  </tr>
                  <tr>
                      <td colspan="2">DIFFERENCE:</td>
                      <td><i class="fa fa-inr"></i>&nbsp<%= @diff == nil ? 0 : @diff ; %></td> 
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <table class="table table-hover table-padding" title="opening_cashes">
                <thead>
                    <th>VALUE</th>
                    <th>QTY</th>
                    <th>TOTAL</th>
                </thead>
                <tbody class='fields closing'>
                  <% if @cashbook_index.previous.present? %>
                  <% @cashbook_index.previous.closing_cashes.each do |credit| %>
                    <tr>
                      <td><%= credit.denomination %></td>
                      <td><%= credit.quantity %></td>
                      <td><%= credit.total %></td>
                    </tr>
                  <% end %>
                  <% end %>
                </tbody>
                 
              </table>
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <td colspan="2">GRAND TOTAL:</td>
                    
                    <td style="text-align: center"><i class="fa fa-inr"></i>&nbsp&nbsp<%= @prev_cash_in_hand %></td>
              
                  </tr>
                  <tr>
                    <td colspan="2">DIFFERENCE:</td>

                    <td style="text-align: center"><i class="fa fa-inr"></i>&nbsp&nbsp<%= @prev_diff == nil ? 0 : @prev_diff ; %></td> 
                  </tr>
                </tbody>
             </table>
            </div>
          </div>
       
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>